--- 
framework: mocha
blacklist:
  - "test/datastore_test.js"
  - "test/adapter_test.js" 
postMerge: 
  pattern: 
  - test/*.js
preMerge: 
  pattern: 
  - test/*.js
preRun: 
  - npm i
postRun: 
  - "node --version"
version: 2.0
